# Generated by Django 5.1.1 on 2024-10-20 19:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_insightor_hourly_rate_delete_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insightor',
            name='certifications',
        ),
        migrations.RemoveField(
            model_name='insightor',
            name='education',
        ),
        migrations.AlterField(
            model_name='insightor',
            name='country',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.CreateModel(
            name='Certifications',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=300)),
                ('issuing_organization', models.CharField(max_length=300)),
                ('issue_date', models.DateField()),
                ('insightor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.insightor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.CharField(max_length=300)),
                ('degree', models.CharField(max_length=300)),
                ('field_of_study', models.CharField(blank=True, max_length=300, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('insightor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.insightor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
