# Generated by Django 5.1.1 on 2024-10-20 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_rename_title_insightor_specialization_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='insightor',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='Request',
        ),
    ]
