# Generated by Django 5.1.1 on 2024-10-20 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_insightor_resume_delete_request'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Certifications',
            new_name='Certification',
        ),
    ]
