# Generated by Django 5.1.1 on 2024-10-24 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_rename_certifications_certification'),
    ]

    operations = [
        migrations.AddField(
            model_name='insightor',
            name='available_days',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='insightor',
            name='work_end',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='insightor',
            name='work_start',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
