# Generated by Django 5.1.1 on 2024-10-28 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_alter_insightor_work_end_alter_insightor_work_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='insightor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='profiles.insightor'),
        ),
        migrations.AlterField(
            model_name='education',
            name='insightor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='profiles.insightor'),
        ),
    ]
