# Generated by Django 5.1.1 on 2024-09-12 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_consultant',
            new_name='is_insightor',
        ),
    ]
